# Dockerfile for MCP development on openSUSE Leap.

FROM psimons/opensuse-docker:leap-lts-11
LABEL maintainer="Peter Simons <simons@cryp.to>"

RUN zypper --non-interactive install -y         \
        ghc-aeson-devel                         \
        ghc-amqp-devel                          \
        ghc-array-devel                         \
        ghc-base-devel                          \
        ghc-bytestring-devel                    \
        ghc-containers-devel                    \
        ghc-filepath-devel                      \
        ghc-http-client-devel                   \
        ghc-http-client-tls-devel               \
        ghc-http-types-devel                    \
        ghc-iconv-devel                         \
        ghc-lambdabot-core-devel                \
        ghc-lambdabot-irc-plugins-devel         \
        ghc-lambdabot-reference-plugins-devel   \
        ghc-lambdabot-social-plugins-devel      \
        ghc-lens-aeson-devel                    \
        ghc-lens-devel                          \
        ghc-lifted-base-devel                   \
        ghc-monad-control-devel                 \
        ghc-mtl-devel                           \
        ghc-regex-tdfa-devel                    \
        ghc-split-devel                         \
        ghc-tagsoup-devel                       \
        ghc-text-devel                          \
        ghc-time-devel                          \
        ghc-unordered-containers-devel          \
        ghc-utf8-string-devel
