# Dockerfile for emu-incident-report development on openSUSE Leap.

FROM psimons/opensuse-docker:leap-lts-11
LABEL maintainer="Peter Simons <simons@cryp.to>"

RUN zypper --non-interactive install -y \
        ghc-aeson-devel                 \
        ghc-attoparsec-devel            \
        ghc-base-compat-devel           \
        ghc-distribution-suse-devel     \
        ghc-dlist-devel                 \
        ghc-extra-devel                 \
        ghc-hashable-devel              \
        ghc-integer-logarithms-devel    \
        ghc-iso8601-time-devel          \
        ghc-optparse-applicative-devel  \
        ghc-pandoc-devel                \
        ghc-pandoc-types-devel          \
        ghc-primitive-devel             \
        ghc-random-devel                \
        ghc-scientific-devel            \
        ghc-tagged-devel                \
        ghc-text-devel                  \
        ghc-th-abstraction-devel        \
        ghc-th-printf-devel             \
        ghc-time-locale-compat-devel    \
        ghc-transformers-compat-devel   \
        ghc-unordered-containers-devel  \
        ghc-uuid-types-devel            \
        ghc-vector-devel
